export const tracks = [
    {
        id: "1",
        artist: "Boys Noize",
        title: "Mvinline",
        version: "Extended Mix",
        label: "Defected",
        image: "",
        trackUrl: "/audio/1.mp3",
        buyUrl: "",
    },
    {
        id: "2",
        artist: "Gorgon City",
        title: "Nobody",
        version: "",
        label: "",
        image: "",
        trackUrl: "/audio/2.mp3",
        buyUrl: "",
    },
    {
        id: "3",
        artist: "Marc Brauner",
        title: "Day Dream",
        version: "",
        label: "Houseum",
        image: "",
        trackUrl: "/audio/3.mp3",
        buyUrl: "",
    },
    {
        id: "4",
        artist: "Cheryl Lynn",
        title: "Got To Be Real",
        version: "Robbie Doherty's 129 Time Edit",
        label: "Columbia",
        image: "",
        trackUrl: "/audio/4.mp3",
        buyUrl: "",
    },
    {
        id: "5",
        artist: "Front Bench & Tom Jarmey",
        title: "Paper Clouds",
        version: "",
        label: "",
        image: "",
        trackUrl: "/audio/5.mp3",
        buyUrl: "",
    },
    {
        id: "6",
        artist: "Stef Davidse",
        title: "If Only",
        version: "",
        label: "",
        image: "",
        trackUrl: "/audio/6.mp3",
        buyUrl: "",
    },
    {
        id: "7",
        artist: "Men I Trust",
        title: "Lauren",
        version: "Oden & Fatzo Edit",
        label: "Sake",
        image: "",
        trackUrl: "/audio/7.mp3",
        buyUrl: "",
    },
    {
        id: "8",
        artist: "John Summit",
        title: "Deep End",
        version: "Extended Mix",
        label: "Defected",
        image: "",
        trackUrl: "/audio/8.mp3",
        buyUrl: "",
    },
];
