export const tracks = [
    {
        id: "1",
        artist: "",
        title: "",
        version: "",
        label: "",
        image: "",
        trackUrl: "",
        buyUrl: "",
    },
    {
        id: "2",
        artist: "",
        title: "",
        version: "",
        label: "",
        image: "",
        trackUrl: "",
        buyUrl: "",
    },
    {
        id: "3",
        artist: "",
        title: "",
        version: "",
        label: "",
        image: "",
        trackUrl: "",
        buyUrl: "",
    },
    {
        id: "4",
        artist: "",
        title: "",
        version: "",
        label: "",
        image: "",
        trackUrl: "",
        buyUrl: "",
    },
    {
        id: "5",
        artist: "",
        title: "",
        version: "",
        label: "",
        image: "",
        trackUrl: "",
        buyUrl: "",
    },
];
